spring.application.name=smart-placement-portal

spring.datasource.url=jdbc:mysql://localhost:3306/smart_placement_portal
spring.datasource.username=root
spring.datasource.password=Situ@123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080